# Generated by Django 4.2.14 on 2025-04-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.IntegerField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=100)),
                ('companyVat', models.IntegerField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=100)),
                ('userPassword', models.CharField(max_length=100)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeLedger.company')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.IntegerField(primary_key=True, serialize=False)),
                ('accountHandleNumber', models.CharField(max_length=10)),
                ('transactionDate', models.DateField()),
                ('transactionAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transactionCurrency', models.CharField(max_length=100)),
                ('transactionDescription', models.CharField(max_length=100)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeLedger.company')),
            ],
        ),
    ]
