# Generated by Django 4.2.14 on 2025-04-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyId',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
