# Generated by Django 5.2 on 2025-04-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userEmail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userPassword',
        ),
    ]
