# Generated by Django 4.2.14 on 2025-04-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0002_alter_company_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyVat',
            field=models.IntegerField(max_length=25, null=True),
        ),
    ]
