# Generated by Django 4.2.14 on 2025-04-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0003_alter_company_companyvat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionId',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
