# Generated by Django 4.2.14 on 2025-04-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
