# Generated by Django 4.2.14 on 2025-04-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0004_alter_transaction_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionId',
            field=models.CharField(max_length=256),
        ),
    ]
