# Generated by Django 4.2.14 on 2025-04-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0005_transaction_id_alter_transaction_transactionid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
