# Generated by Django 4.2.14 on 2025-04-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0006_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=256)),
                ('accountHandleNumber', models.CharField(max_length=10)),
                ('transactionDate', models.DateField()),
                ('transactionAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transactionCurrency', models.CharField(max_length=100)),
                ('transactionDescription', models.CharField(max_length=100)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeLedger.company')),
            ],
        ),
    ]
