# Generated by Django 4.2.14 on 2025-04-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0007_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyVat',
            field=models.IntegerField(null=True),
        ),
    ]
