# Generated by Django 4.2.14 on 2025-04-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0008_alter_company_companyvat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='companyVat',
        ),
    ]
