# Generated by Django 4.2.14 on 2025-04-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0009_remove_company_companyvat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='companyId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='accountHandleNumber',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
