# Generated by Django 4.2.14 on 2025-04-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0010_remove_transaction_id_alter_company_companyid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Postings',
        ),
        migrations.RenameField(
            model_name='postings',
            old_name='transactionAmount',
            new_name='postAmount',
        ),
        migrations.RenameField(
            model_name='postings',
            old_name='transactionCurrency',
            new_name='postCurrency',
        ),
        migrations.RenameField(
            model_name='postings',
            old_name='transactionDate',
            new_name='postDate',
        ),
        migrations.RenameField(
            model_name='postings',
            old_name='transactionDescription',
            new_name='postDescription',
        ),
        migrations.RenameField(
            model_name='postings',
            old_name='transactionId',
            new_name='postId',
        ),
    ]
