# Generated by Django 4.2.14 on 2025-04-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0011_rename_transaction_postings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='companyId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='postings',
            old_name='postId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='postings',
            name='accountHandleNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postings',
            name='postAmount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
