# Generated by Django 4.2.14 on 2025-04-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0012_rename_companyid_company_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postings',
            old_name='companyId',
            new_name='companyId_id',
        ),
    ]
