# Generated by Django 4.2.14 on 2025-04-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0013_rename_companyid_postings_companyid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postings',
            old_name='companyId_id',
            new_name='company',
        ),
    ]
