# Generated by Django 4.2.14 on 2025-04-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeLedger', '0014_rename_companyid_id_postings_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='companyId',
        ),
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(to='SafeLedger.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('accountant', 'Accountant'), ('customer', 'Customer'), ('superuser', 'Superuser')], default='customer', max_length=20),
        ),
    ]
